language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - DEPOPTS="lwt"
    - PACKAGE="notty"
    - FORK_USER=yallop
    - FORK_BRANCH=4.06
  matrix:
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
notifications:
  email: false
